export let levelTitle = [
    ["[ LEVEL 1: SHATTERED REFLECTIONS ]"],
    ["[ LEVEL 2: WHISPERING HALLS ]"],
    ["[ LEVEL 3: PHANTOM PURSUIT ]"],
    ["[ LEVEL ?: G̶̨͙͕̮͙̠̹̬̰̊̾̓̉̈́̔͠͝A̷̢͕̰͉̭͔͒̓̊͌/̸̧̨̡̢̮̦͈͍̬̺͉͙̌̏͐͑̿̍͜͝/̵̙̣̥̄͑̉͋̈́͊̈́͆̋͝M̷̟͍̤͋̏̋̿͂͌̌͂̋̽͋͌̄̚̕.̸̡̡̹̻̥̄͋E̵̡̢̟͍̯̤̪̮̙̮̎͗ͅ ̴̧͎̤̱̟͕̼̙̺̮̼͓̞̜̀̿̾̔̈͒͆̎́͛̄̂̾̿͜͝Ơ̵͖̼̤̝̘̞͕͔̻̖̓̈́͛̎̇̅̔͊̏̽͠ͅV̵̡͉̳͈͍̤̜͖̥̈́͐/̵̛̤̣̳͈͎̼͕̫͌͆̒̒̑̿̄/̶̥̫̞̙̘̂̽̈̒͜͠E̵̪̞͆̓͛͐͘.̶̡̼̻̹̖̯̮͎̪̺̪̥̱̗͈͐́̍̄̈̒͑͛̏.̸̧̢̭͖̝͎͘ͅ.̵̯͇̗͚͚̻̀̌̉͗̋͜R̵̳̫̱̪̹̪̗̞͎̙̹̺̽̄́̾̈́̂͘ ]"]
]

export let levelStory = [
    ["In the oppressive silence of the moonlit night, I found myself trapped in an ethereal nightmare. The cold walls of the haunted maze pressed in, and with every hurried step, I could sense a malevolent presence gaining on me. The air grew thick with the echoes of ghostly whispers as I navigated the labyrinthine corridors, haunted by distorted reflections of my own fears.\n\nThe ghostly figure, draped in shadows, pursued relentlessly, its chilling whispers echoing through the endless maze. Panic surged as I raced through shifting passages, the walls closing in and warping with each breath. Desperation fueled my escape as the ghost's ethereal fingers grazed the edges of my consciousness.\n\nAs I sprinted towards the exit, a crescendo of haunting wails surrounded me. Heart pounding, I reached the maze's edge, and with a final glance over my shoulder, I awoke gasping, the echoes of ghostly laughter fading into the recesses of my fading nightmare."],
    ["Through the haze of darkness, I stumbled into a haunted maze, its ghostly corridors winding into an abyss. A spectral figure, a ghastly apparition with hollow eyes, pursued me relentlessly. Each turn revealed more oppressive shadows that seemed to taunt and mock my frantic attempts to escape.\n\nThe maze whispered secrets of forgotten fears, the ghostly presence embodying the manifestation of my deepest nightmares. A chilling wind carried the ghost's malevolent laughter as I raced through the narrowing passages, my breaths matching the rhythm of my pounding heart.\n\nJust as the ghost's skeletal fingers grazed the edges of my sanity, I burst into the open. Gasping for air, I jolted awake, the oppressive maze fading into the shadows of my subconscious. The haunting laughter lingered briefly before dissipating into the waking world."],
    ["In the disorienting maze of my nightmares, I found myself pursued by a relentless phantom. Its ethereal form glided effortlessly through the twisted corridors, shadows dancing at the edges of my vision. Panic set in as I navigated the maze's treacherous turns, the ghostly specter closing the gap with every fleeting moment.\n\nThe air crackled with a malevolent energy, and the walls seemed to pulse with the rhythm of my escalating fear. Desperation fueled my escape as I raced towards the elusive exit, the ghost's chilling whispers reverberating through the haunted maze.\n\nJust as the spectral figure loomed dangerously close, I burst into wakefulness, the nightmare disintegrating like mist. The oppressive maze melted away, leaving only the echoes of ghostly laughter fading into the recesses of my subconscious. I lay in bed, heart pounding, grateful for the sanctuary of waking reality."],
    ["y̵̧͕̻̘̹̮͍̌̉̈́̑̃͝.̵͕̳̹̘͍͍̖̫͙̮̺͙͆̅͆͐̊.̷̢͓͍͕̗͔͕͑̾̅͌͜o̷̡̨̠͕̞͖̣̻̓U̷̹͑͒̽͝ ̸̢̛̙̘̯̻͙͈͂͆̿͛́́Ẇ̴̭̮̰̙͔̰̟̼̲̗̞̬͂̌̒̈̈́̅͠ͅI̷̧̱̺̫͋̌.̵̨̧̛̛̪̰̪̘̦̲̩̫̦̣̠̝̌̀̔̃͐̔̔̈́̂̄͐̍͜͝.̴̨̻̻̱̓̉͒̓͂̕͜͝/̷̟͚̥͚͚͇͔̮̥̪͉̘̙̯͔̌͐̔͌̏̋̐̈́̒̀̐̌̅̅͠N̶̨̡̡̢̮͚̬̜̘̬͉̠͚̱̅̈ͅ.̶̛͉̺̖̄̾̏̈̓̋́͊͘\n\n.̸̨̢̫̭̺̺̻̿ͅỊ̶̤̤͉̬͇̀̀̽̊̍̎͒̓͠.̷̝̼̫̒̋̄̎̅̆̓̚.̶̧̡͔̻̠͈̪̦͍̖͆͒͛̏͛̋̉̂̓̚͘͜͝ͅ/̶̟͖̭̪͈͙̹̋̏͌G̵̨̨̩̙̼̫̭̪͉̜̿̍̉͊̓̋͌̕̕.̸͖̰̱͎̗͇̩͈̳̗̫͈͋̿.̸̖̂̈́̈́͆̓ ̴̜̜͔̳̘̺̺̈́̿̐̽͒̇͘M̸̢̡̛̛̖̹͈̘͈̭̫̐̈́̎͑̋̈́̇͂̎̈́͘͝'̴̧̻̪̳̣̰̪̹̲͖̥͈͚̩̠̔̌̋̈́́̍̒̀̈́͋̅̅͘̕.̶̧̨̰͇̥̜̫̝̰̓̎̿͛͆̋̿Į̴̢͇̤̭̪͚̤̪̤̆͌̽͐͝Ś̷̞̺͙͚̣̺̠̞̫͔̹͌T̷̹̣̦̑̈́͊́͊͛̎̈́͋̏͆̈.̴̡̪̫͍͉͇͎͕̿͑̄̒̐̔́̉̆̉̚͘.̴̨̡̹̱͕͕̣̪̳͊͘̕͜͜ͅẠ̸͉̱͇̼͑́̌͐K̴̗̳͌Ė̶̮͉͍̦̥̘̫̲̎̋̐.̴̧̲͈͓̬͕̬̞̬̪̌̈́̊̂̅̽̚̚̕/̵̢̫̣͖̪͙͒͂͗͠.̵̬̫̤̤̯̆̾͋̅̑͆́̍̿́͋͑\n\nĘ̶̛̉̔͂̓͗̅̈͌.̷̧͍̜͇̺̪͈̩̜́̍.̵̧̳̭̤͔͎͌̿͊͗͂N̸̪̜̫͆̄̌͐̀͛̿̔̔̑̑͠J̶̢̨̺̣̹̘̲̺̤̝̪͉̲̙̈́̆̂̈͑͑͂̈́͂̏̾̒O̶̟̝̬̐͑͒̿Ȳ̶͔̮̘̼̟͍͕̙̦͕̠̼͍̟.̶̨̢̮͎̇̈́́͜.̸̭̤͓̮͖͎̼̘̪͈̪̰́̉̒̑̌͑!̸̢̛̛̯̙̱̻͎̤̓̂̃̏͆͌͝"]
]